version: 2
jobs:
  build:
    docker:
      - image: yarnpkg/node-yarn
    working_directory: ~/repo
    branches:
      only:
        - master

    steps:
      - checkout
      - run: sudo apt-get update -y && apt-get install -y kubectl
      - run: yarn install
      - run: yarn run gulp build 

