version: 2
jobs:
  build:
    docker:
      - image: yarnpkg/node-yarn
    working_directory: ~/repo
    branches:
      only:
        - master

    steps:
      - checkout
      - kube-orb/install-kubectl
      - run: yarn install
      - run: yarn run gulp build 
orbs:
  kube-orb: circleci/kubernetes@x.y.z
