version: 2
jobs:
  build:
    docker:
      - image: yarnpkg/node-yarn
    working_directory: ~/repo
    branches:
      only:
        - master

    steps:
      - checkout
      - kube-orb/install-kubectl
      - run: echo "${KUBECONFIG_FILE}" | base64 --decode >> kubeconfig.json
      - run: export KUBECONFIG=./kubeconfig.json
      - run: kubectl get pods -n kyma-system
      - run: yarn install
      - run: yarn run gulp build 
